// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDumGRTp0NzsL4wZ7vyk8JFJIV34nRtfJE',
    appId: '1:436254686547:web:3510ebf2d1c47cebb8f5a6',
    messagingSenderId: '436254686547',
    projectId: 'mae-project-9d22f',
    authDomain: 'mae-project-9d22f.firebaseapp.com',
    databaseURL: 'https://mae-project-9d22f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-project-9d22f.firebasestorage.app',
    measurementId: 'G-FVYNM5Z1M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCth9R98iDWZ_H5R5_u7qhNTuUKX8NXb3U',
    appId: '1:436254686547:android:4a18374296ba5a8bb8f5a6',
    messagingSenderId: '436254686547',
    projectId: 'mae-project-9d22f',
    databaseURL: 'https://mae-project-9d22f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-project-9d22f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQ485_1EZ-tVXU_DgiJYqQG9zCKgZikY',
    appId: '1:436254686547:ios:c22c63123ce2881ab8f5a6',
    messagingSenderId: '436254686547',
    projectId: 'mae-project-9d22f',
    databaseURL: 'https://mae-project-9d22f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-project-9d22f.firebasestorage.app',
    iosBundleId: 'com.example.aphub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQ485_1EZ-tVXU_DgiJYqQG9zCKgZikY',
    appId: '1:436254686547:ios:c22c63123ce2881ab8f5a6',
    messagingSenderId: '436254686547',
    projectId: 'mae-project-9d22f',
    databaseURL: 'https://mae-project-9d22f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-project-9d22f.firebasestorage.app',
    iosBundleId: 'com.example.aphub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDumGRTp0NzsL4wZ7vyk8JFJIV34nRtfJE',
    appId: '1:436254686547:web:d6e1a7cdeac863f4b8f5a6',
    messagingSenderId: '436254686547',
    projectId: 'mae-project-9d22f',
    authDomain: 'mae-project-9d22f.firebaseapp.com',
    databaseURL: 'https://mae-project-9d22f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mae-project-9d22f.firebasestorage.app',
    measurementId: 'G-2K4SDC3RG1',
  );

}